apiVersion: v1
kind: Service
metadata:
  labels:
    app: sound-api
  name: sound-api
spec:
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 9095
      nodePort: 8082
  selector:
    app: sound-api
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sound-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sound-api
    spec:
      containers:
        - name: sound-api
          image: {{HUB}}/sound/sound_api:1.0.1
          ports:
            - containerPort: 9095
